name: Reclutamiento de Agente

on: push

jobs: 
    reporte-de-recletamiento:
        runs-on: ubuntu-latest

        steps:
            - name: El agente se presenta
              run: echo "Hola, soy el agente de reclutamiento y estoy listo para ayudar en el proceso de selección."